export class Orders{
  constructor(
    public id:any,
    public id_userperorder:any,
    public id_seller:any,
    public id_school:any,
    public id_ship:any,
    public id_ship_type:any,
    public id_order_type:any,
    public id_city:any,
    public consecutivo:any,
    public contrato:any,
    public code:any,
    public guia:any,
    public previous_order:any,
    public created_at:any,
    public updated_at:any,
    public canceled_at:any,
    public date_application:any,
    public date_ship:any,
    public date_return:any,
    public observations:any,
    public ship_name:any,
    public ship_to:any,
    public ship_address:any,
    public ship_phone:any,
    public total:any,
    public facturado:any,
    public material:any,
    public item:any,
    public archivo_listas:any,
    public state:any
  ){}
}
